# Generated by Django 5.2.3 on 2025-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gachaticket',
            options={'verbose_name': 'ガチャチケット', 'verbose_name_plural': 'ガチャチケット一覧'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': '高評価', 'verbose_name_plural': '高評価一覧'},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'verbose_name': 'システムログ', 'verbose_name_plural': 'システムログ一覧'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'ユーザー行動履歴', 'verbose_name_plural': 'ユーザー行動履歴一覧'},
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='video_url',
        ),
        migrations.AddField(
            model_name='attraction',
            name='video_file',
            field=models.FileField(blank=True, help_text='MP4などの動画ファイルをアップロードしてください。', null=True, upload_to='videos/', verbose_name='紹介動画ファイル'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='status',
            field=models.CharField(choices=[('available', '空き'), ('normal', '普通'), ('crowded', '混雑'), ('preparing', '準備中'), ('soon', '開演間近'), ('showing', '上演中'), ('closed', '閉店')], default='available', max_length=20, verbose_name='現在の状態'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', '来場者'), ('admin', '管理者'), ('gacha', 'ガチャ職員'), ('signage', 'サイネージ')], default='visitor', max_length=10, verbose_name='役割'),
        ),
    ]
