# Generated by Django 5.2.3 on 2025-06-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_gachaticket_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='hls_playlist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HLS再生リストパス'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='video_file',
            field=models.FileField(blank=True, help_text='MP4などの動画ファイルをアップロードしてください。', null=True, upload_to='videos/originals/', verbose_name='紹介動画ファイル'),
        ),
    ]
