# Generated by Django 5.2.3 on 2025-06-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_attraction_hls_playlist_alter_attraction_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_attractions',
            field=models.ManyToManyField(blank=True, help_text='役割が「出し物職員」の場合に、担当する出し物を設定してください。', to='manager.attraction', verbose_name='担当出し物'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', '来場者'), ('admin', '管理者'), ('gacha', 'ガチャ職員'), ('signage', 'サイネージ'), ('staff', '出し物職員')], default='visitor', max_length=10, verbose_name='役割'),
        ),
    ]
