# Generated by Django 5.2.3 on 2025-06-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_user_managed_attractions_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('icon', models.CharField(blank=True, help_text='Remix Iconの名前を入力してください (例: ri-restaurant-line)', max_length=50, verbose_name='アイコン名')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ一覧',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='tags',
            field=models.ManyToManyField(blank=True, to='manager.tag', verbose_name='タグ'),
        ),
    ]
