# Generated by Django 5.2.3 on 2025-06-14 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_tag_attraction_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='滞在時間(秒)'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='入室時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退室時間'),
        ),
    ]
